/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciorepaso.vista;

import java.awt.event.ActionListener;
import ejerciciorepaso.modelo.Posicion;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author samo_
 */
public class AniadirJugador extends javax.swing.JPanel {

    /**
     * Creates new form AniadirJugador
     */
    public AniadirJugador() {
        initComponents();
    }

    public void addControlador(ActionListener e){
    
        jButton_aniadir.addActionListener(e);
        jButton_cancelar.addActionListener(e);
        
        jButton_aniadir.setActionCommand("aniadir");
        jButton_cancelar.setActionCommand("cancelar");
    
    }
    
    public int getDorsal(){return (Integer) jSpinner_dorsal.getValue();}
    public String getNombre(){return jTextField_nombre.getText();}
    public String getAltura(){return jFormattedTextField_altura.getText();}
    public String getPosicion(){return jComboBox_posicion.getSelectedItem().toString();}
    public boolean getSuplente(){return jCheckBox_suplente.isSelected();}
    
    private void addValores(){
        
        jComboBox_posicion.setModel(new DefaultComboBoxModel(Posicion.values()));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_dorsal = new javax.swing.JLabel();
        jSpinner_dorsal = new javax.swing.JSpinner();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_altura = new javax.swing.JLabel();
        jFormattedTextField_altura = new javax.swing.JFormattedTextField();
        jLabel_posicion = new javax.swing.JLabel();
        jComboBox_posicion = new javax.swing.JComboBox<>();
        jLabel_suplente = new javax.swing.JLabel();
        jCheckBox_suplente = new javax.swing.JCheckBox();
        jButton_cancelar = new javax.swing.JButton();
        jButton_aniadir = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(6, 2));

        jLabel_dorsal.setText("Dorsal");
        add(jLabel_dorsal);

        jSpinner_dorsal.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 4.0d, 0.01d));
        add(jSpinner_dorsal);

        jLabel_nombre.setText("Nombre");
        add(jLabel_nombre);
        add(jTextField_nombre);

        jLabel_altura.setText("Altura");
        add(jLabel_altura);
        add(jFormattedTextField_altura);

        jLabel_posicion.setText("Posicion");
        add(jLabel_posicion);

        addValores();
        add(jComboBox_posicion);

        jLabel_suplente.setText("Suplente");
        add(jLabel_suplente);

        jCheckBox_suplente.setText("Es suplente");
        add(jCheckBox_suplente);

        jButton_cancelar.setText("Cancelar");
        add(jButton_cancelar);

        jButton_aniadir.setText("Añadir");
        add(jButton_aniadir);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aniadir;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JCheckBox jCheckBox_suplente;
    private javax.swing.JComboBox<String> jComboBox_posicion;
    private javax.swing.JFormattedTextField jFormattedTextField_altura;
    private javax.swing.JLabel jLabel_altura;
    private javax.swing.JLabel jLabel_dorsal;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_posicion;
    private javax.swing.JLabel jLabel_suplente;
    private javax.swing.JSpinner jSpinner_dorsal;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables

    public void resetearVista() {
    
        jCheckBox_suplente.setSelected(false);
        jComboBox_posicion.setSelectedIndex(0);
        jFormattedTextField_altura.setText("");
        //jSpinner_dorsal.setValue("0");
        jTextField_nombre.setText("");
    
    }
}
