/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciorepaso.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author samo_
 */
public class Vista extends javax.swing.JPanel {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }
    
    public void addControlador(ActionListener e) {
    
        btn_aniadirEstadistica.addActionListener(e);
        btn_aniadirJugador.addActionListener(e);
        btn_verCalendario.addActionListener(e);
        btn_verEstadistica.addActionListener(e);
        
        btn_aniadirEstadistica.setActionCommand("aniadirEspecialidad");
        btn_aniadirJugador.setActionCommand("aniadirJugador");
        btn_verCalendario.setActionCommand("verCalendario");
        btn_verEstadistica.setActionCommand("verEspecialidad");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_aniadirJugador = new javax.swing.JButton();
        btn_aniadirEstadistica = new javax.swing.JButton();
        btn_verEstadistica = new javax.swing.JButton();
        btn_verCalendario = new javax.swing.JButton();

        btn_aniadirJugador.setText("Añadir Jugador");
        add(btn_aniadirJugador);

        btn_aniadirEstadistica.setText("Añadir Estadisticas Jugador");
        add(btn_aniadirEstadistica);

        btn_verEstadistica.setText("Ver Estadisticas");
        add(btn_verEstadistica);

        btn_verCalendario.setText("Ver Calendario");
        add(btn_verCalendario);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aniadirEstadistica;
    private javax.swing.JButton btn_aniadirJugador;
    private javax.swing.JButton btn_verCalendario;
    private javax.swing.JButton btn_verEstadistica;
    // End of variables declaration//GEN-END:variables
}
