/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciorepasoevents.vista;

import ejerciciorepasoevents.modelo.ModeloTabla;
import java.awt.event.ActionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author samo_
 */
public class Vista extends javax.swing.JPanel {

    /**
     * Creates new form Vista
     */
    public Vista() {
        
        initComponents();
    }
    
    public void setModeloAtributos(TableModel modelo) {
        tabla_articulos.setModel(modelo);
    }
    
    public void setModeloDerecha(TableModel modelo) {
        tabla_derecha.setModel(modelo);
    }
    
    public TableModel getModeloAtributos() {
        return tabla_articulos.getModel();
    }
    
    public TableModel getModeloDerecha() {
        return tabla_derecha.getModel();
    }
    
    public void addControlador(ActionListener e){
    
        btn_agregar.addActionListener(e);
        btn_eliminar.addActionListener(e);
        
        btn_agregar.setActionCommand("agregar");
        btn_eliminar.setActionCommand("eliminar");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_derecha = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_articulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(tabla_derecha);

        add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jScrollPane2.setViewportView(tabla_articulos);

        add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        btn_eliminar.setText("eliminar");
        jPanel1.add(btn_eliminar);

        btn_agregar.setText("agregar");
        jPanel1.add(btn_agregar);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_articulos;
    private javax.swing.JTable tabla_derecha;
    // End of variables declaration//GEN-END:variables

}
