/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciotablabd.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author samo_
 */
public class VistaAniadirLibro extends javax.swing.JPanel {

    /**
     * Creates new form VistaAniadirLibro
     */
    public VistaAniadirLibro() {
        initComponents();
    }
    
    public String getISBN(){return jTextField_isbn.getText();}
    public String getNumPagina(){return jTextField_numPagina.getText();}
    public String getTitulo(){return jTextField_titulo.getText();}
    
    public void addControlador(ActionListener e){
    
        btn_aniadir.addActionListener(e);
        
        btn_aniadir.setActionCommand("aniadir");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_isbn = new javax.swing.JLabel();
        jTextField_isbn = new javax.swing.JTextField();
        jLabel_numPagina = new javax.swing.JLabel();
        jTextField_numPagina = new javax.swing.JTextField();
        jLabel_titulo = new javax.swing.JLabel();
        jTextField_titulo = new javax.swing.JTextField();
        btn_aniadir = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel_isbn.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel_isbn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField_isbn, gridBagConstraints);

        jLabel_numPagina.setText("Número Páginas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel_numPagina, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField_numPagina, gridBagConstraints);

        jLabel_titulo.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel_titulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField_titulo, gridBagConstraints);

        btn_aniadir.setText("Agregar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btn_aniadir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aniadir;
    private javax.swing.JLabel jLabel_isbn;
    private javax.swing.JLabel jLabel_numPagina;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JTextField jTextField_isbn;
    private javax.swing.JTextField jTextField_numPagina;
    private javax.swing.JTextField jTextField_titulo;
    // End of variables declaration//GEN-END:variables
}
