/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciotablabd.vista;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samo_
 */
public class Vista extends javax.swing.JPanel {

    private DefaultTableModel modelo;

    /**
     * Creates new form Vista
     */
    public Vista() {
        modelo = new DefaultTableModel();
        initComponents();
    }
    
    public void addControlador(ActionListener e){
        
        btn_aniadir.addActionListener(e);
        btn_eliminar.addActionListener(e);
        btn_salir.addActionListener(e);
        btn_ejecutar.addActionListener(e);

        btn_aniadir.setActionCommand("aniadir");
        btn_eliminar.setActionCommand("eliminar");
        btn_salir.setActionCommand("salir");
        btn_ejecutar.setActionCommand("ejecutar");

    }
    
    public String getTextInsertarcodigo(){return text_insertarCodigo.getText();}
    
    public void addCabecera(Object[] cabecera){
        modelo.setColumnIdentifiers(cabecera);
    }
    
    public void addFila(Object[] fila){
        modelo.addRow(fila);
    }
    
    public void vaciarTabla(){
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_aniadir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        text_insertarCodigo = new javax.swing.JTextField();
        btn_ejecutar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btn_aniadir.setText("Añadir");
        jPanel1.add(btn_aniadir);

        btn_eliminar.setText("Eliminar");
        jPanel1.add(btn_eliminar);

        btn_salir.setText("Salir");
        jPanel1.add(btn_salir);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(text_insertarCodigo, java.awt.BorderLayout.CENTER);

        btn_ejecutar.setText("Ejecutar");
        jPanel2.add(btn_ejecutar, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aniadir;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_insertarCodigo;
    // End of variables declaration//GEN-END:variables
}
