/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotpv.Vista;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import proyectotpv.Modelo.BigPanel;

/**
 *
 * @author samo_
 */
public class VistaPrincipal extends javax.swing.JPanel {

    private final BigPanel barra;
    private JButton btnSalir;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(BigPanel barra) {
        initComponents();
        this.barra = barra;
        this.add(barra, BorderLayout.NORTH);
        btnSalir = barra.getBotonSalir();
        
    }
    
    public void controlador(ActionListener e){
        .addActionListener(e);
        
        .setActionCommand("salir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
