/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate.vista;

/**
 *
 * @author alumno2damdiurno
 */
public class AgregarCliente extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCliente
     */
    public AgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 2));

        jLabelNombre.setText("Nombre");
        add(jLabelNombre);

        jTextField1.setText("jTextField1");
        add(jTextField1);

        jLabelDireccion.setText("Direccion");
        add(jLabelDireccion);

        jTextField2.setText("jTextField2");
        add(jTextField2);

        jLabelFecha.setText("Fecha");
        add(jLabelFecha);
        add(jDateChooser1);

        jButtonGuardar.setText("Guardar");
        add(jButtonGuardar);

        jButtonSalir.setText("Salir");
        add(jButtonSalir);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
