/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author alumno2damdiurno
 */
public class VistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }
    
    public void addControlador(ActionListener e) {
        
        btn_client.addActionListener(e);
        btn_director.addActionListener(e);
        btn_pelicula.addActionListener(e);
        btn_salir.addActionListener(e);
        
        btn_client.setActionCommand("cliente");
        btn_director.setActionCommand("director");
        btn_pelicula.setActionCommand("pelicula");
        btn_salir.setActionCommand("salir");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraHerramienta = new javax.swing.JToolBar();
        btn_client = new javax.swing.JButton();
        btn_director = new javax.swing.JButton();
        btn_pelicula = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        BarraHerramienta.setRollover(true);

        btn_client.setText("Cliente");
        btn_client.setFocusable(false);
        btn_client.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_client.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramienta.add(btn_client);

        btn_director.setText("Director");
        btn_director.setFocusable(false);
        btn_director.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_director.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramienta.add(btn_director);

        btn_pelicula.setText("Pelicula");
        btn_pelicula.setFocusable(false);
        btn_pelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pelicula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramienta.add(btn_pelicula);

        btn_salir.setText("Salir");
        btn_salir.setFocusable(false);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BarraHerramienta.add(btn_salir);

        add(BarraHerramienta, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarraHerramienta;
    private javax.swing.JButton btn_client;
    private javax.swing.JButton btn_director;
    private javax.swing.JButton btn_pelicula;
    private javax.swing.JButton btn_salir;
    // End of variables declaration//GEN-END:variables

}
