/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciomostrartabla.vista;

import ejerciciomostrartabla.modelo.ModeloTabla;
import javax.swing.JTable;

/**
 *
 * @author samo_
 */
public class Tabla extends javax.swing.JPanel {

    /**
     * Creates new form Tabla
     */
    
    private JTable tabla;
    private ModeloTabla modelo;
    
    public Tabla() {
        
        modelo = new ModeloTabla();
        tabla.setModel(modelo);
        initComponents();
    }
    
    public void aniadirFila(Object[] fila){
        modelo.addRow(fila);
    }
    
    public void aniadirCabecera(Object[] cabecera){
        modelo.setColumnIdentifiers(cabecera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
