/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repasoexamen1.vista;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author alumno2damdiurno
 */
public class VistaPrincipal extends javax.swing.JPanel {

    private VistaPrincipal vista;
    private ImageIcon buscar, aniadir;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(boolean activo) {
        initComponents();
        iniciarBotones(activo);
        
    }
    
    private void iniciarBotones(boolean activo) {
        
        aniadir = new ImageIcon("img/add.jpeg");
        buscar = new ImageIcon("img/buscar.jpeg");
        
        jButtonAniadir.setIcon(aniadir);
        jButtonBuscar.setIcon(buscar);
        
        if (!activo){
            
            jButtonAniadir.setEnabled(false);
            
        }
        
    }
    
    public void addControlador(ActionListener e){
        
        jButtonAniadir.addActionListener(e);
        jButtonBuscar.addActionListener(e);
        
        jButtonAniadir.setActionCommand("aniadir");
        jButtonBuscar.setActionCommand("buscar");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenido = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAnioPublicacion = new javax.swing.JLabel();
        jFormattedTextFieldAnioPublicacion = new javax.swing.JFormattedTextField();
        jLabelEditorial = new javax.swing.JLabel();
        jTextFieldEditorial = new javax.swing.JTextField();
        jLabelPrestado = new javax.swing.JLabel();
        jCheckBoxPrestado = new javax.swing.JCheckBox();
        jToolBar = new javax.swing.JToolBar();
        jButtonAniadir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelContenido.setLayout(new java.awt.GridLayout(5, 2));

        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitulo.setText("Título: ");
        jPanelContenido.add(jLabelTitulo);
        jPanelContenido.add(jTextFieldTitulo);

        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAutor.setText("Autor: ");
        jPanelContenido.add(jLabelAutor);
        jPanelContenido.add(jTextFieldAutor);

        jLabelAnioPublicacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAnioPublicacion.setText("Año de Publicación: ");
        jPanelContenido.add(jLabelAnioPublicacion);

        jFormattedTextFieldAnioPublicacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        jPanelContenido.add(jFormattedTextFieldAnioPublicacion);

        jLabelEditorial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEditorial.setText("Editorial: ");
        jPanelContenido.add(jLabelEditorial);
        jPanelContenido.add(jTextFieldEditorial);

        jLabelPrestado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrestado.setText("Prestado: ");
        jPanelContenido.add(jLabelPrestado);
        jPanelContenido.add(jCheckBoxPrestado);

        add(jPanelContenido, java.awt.BorderLayout.CENTER);

        jToolBar.setRollover(true);

        jButtonAniadir.setFocusable(false);
        jButtonAniadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAniadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButtonAniadir);

        jButtonBuscar.setFocusable(false);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButtonBuscar);

        add(jToolBar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JCheckBox jCheckBoxPrestado;
    private javax.swing.JFormattedTextField jFormattedTextFieldAnioPublicacion;
    private javax.swing.JLabel jLabelAnioPublicacion;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEditorial;
    private javax.swing.JLabel jLabelPrestado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditorial;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

    public int getAnio() {
        return Integer.valueOf(jFormattedTextFieldAnioPublicacion.getText());
    }

    public String getAutor() {
        return jTextFieldAutor.getText();
    }

    public String getEditorial() {
        return jTextFieldEditorial.getText();
    }

    public boolean getPrestado() {
        return jCheckBoxPrestado.isSelected();
    }
    
    public String getTitulo(){
        return jTextFieldTitulo.getText();
    }

}
