/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareacoches.vistas;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author samo_
 */
public class Vista extends javax.swing.JPanel {

    public enum Tipos{MINI, UTILITARIO, FAMILIAR, DEPORTIVO};
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_asegurar = new javax.swing.ButtonGroup();
        jLabel_modelo = new javax.swing.JLabel();
        jTextField_modelo = new javax.swing.JTextField();
        jLabel_color = new javax.swing.JLabel();
        jTextField_color = new javax.swing.JTextField();
        jLabel_matrucula = new javax.swing.JLabel();
        jTextField_matricula = new javax.swing.JTextField();
        jRadioButton_todoRiesgo = new javax.swing.JRadioButton();
        jRadioButton_terceros = new javax.swing.JRadioButton();
        jLabel_fabricacion = new javax.swing.JLabel();
        jFormattedTextField_fabricacion = new javax.swing.JFormattedTextField();
        jLabel_tipo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel_pintura = new javax.swing.JLabel();
        jCheckBox_metalizado = new javax.swing.JCheckBox();
        jButton_aceptar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del coche"));
        setLayout(new java.awt.GridLayout(8, 2));

        jLabel_modelo.setText("Modelo");
        add(jLabel_modelo);
        add(jTextField_modelo);

        jLabel_color.setText("Color");
        add(jLabel_color);
        add(jTextField_color);

        jLabel_matrucula.setText("Matrícula");
        add(jLabel_matrucula);
        add(jTextField_matricula);

        buttonGroup_asegurar.add(jRadioButton_todoRiesgo);
        jRadioButton_todoRiesgo.setMnemonic('t');
        jRadioButton_todoRiesgo.setText("A todo riesgo");
        add(jRadioButton_todoRiesgo);

        buttonGroup_asegurar.add(jRadioButton_terceros);
        jRadioButton_terceros.setMnemonic('t');
        jRadioButton_terceros.setText("A terceros");
        add(jRadioButton_terceros);

        jLabel_fabricacion.setText("Año de fabricación");
        add(jLabel_fabricacion);

        try {
            jFormattedTextField_fabricacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(jFormattedTextField_fabricacion);

        jLabel_tipo.setText("Tipo de coche");
        add(jLabel_tipo);

        jComboBox1.setModel(new DefaultComboBoxModel(Tipos.values()));
        add(jComboBox1);

        jLabel_pintura.setText("Tipo de pintura");
        add(jLabel_pintura);

        jCheckBox_metalizado.setText("Metalizado");
        add(jCheckBox_metalizado);

        jButton_aceptar.setText("Aceptar");
        add(jButton_aceptar);

        jButton_cancelar.setText("Cancelar");
        add(jButton_cancelar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_asegurar;
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JCheckBox jCheckBox_metalizado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField_fabricacion;
    private javax.swing.JLabel jLabel_color;
    private javax.swing.JLabel jLabel_fabricacion;
    private javax.swing.JLabel jLabel_matrucula;
    private javax.swing.JLabel jLabel_modelo;
    private javax.swing.JLabel jLabel_pintura;
    private javax.swing.JLabel jLabel_tipo;
    private javax.swing.JRadioButton jRadioButton_terceros;
    private javax.swing.JRadioButton jRadioButton_todoRiesgo;
    private javax.swing.JTextField jTextField_color;
    private javax.swing.JTextField jTextField_matricula;
    private javax.swing.JTextField jTextField_modelo;
    // End of variables declaration//GEN-END:variables
}
