/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectodi.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author alumno2damdiurno
 */
public class Vista extends javax.swing.JPanel {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }
    
    public void addControladror(ActionListener e){
    
        btn_entrar.addActionListener(e);
        btn_salir.addActionListener(e);
        
        btn_entrar.setActionCommand("entrar");
        btn_salir.setActionCommand("salir");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLogearse = new javax.swing.JPanel();
        txt_accesoTPV = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_entrar = new javax.swing.JButton();
        combo_usuarios = new javax.swing.JComboBox();
        txt_contrasenia = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        ediText_contrasenia = new javax.swing.JPasswordField();

        setLayout(new java.awt.BorderLayout());

        panelLogearse.setLayout(new java.awt.GridBagLayout());

        txt_accesoTPV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_accesoTPV.setText("Acceso al terminal TPV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(txt_accesoTPV, gridBagConstraints);

        btn_salir.setText("Salir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(btn_salir, gridBagConstraints);

        btn_entrar.setText("Entrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(btn_entrar, gridBagConstraints);

        combo_usuarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(combo_usuarios, gridBagConstraints);

        txt_contrasenia.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(txt_contrasenia, gridBagConstraints);

        txt_usuario.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(txt_usuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelLogearse.add(ediText_contrasenia, gridBagConstraints);

        add(panelLogearse, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox combo_usuarios;
    private javax.swing.JPasswordField ediText_contrasenia;
    private javax.swing.JPanel panelLogearse;
    private javax.swing.JLabel txt_accesoTPV;
    private javax.swing.JLabel txt_contrasenia;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
